# Required
version: 2

# Sphinx
sphinx:
  configuration: doc/conf.py
  fail_on_warning: false

# Install current library
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

