name: shoot

channels:
  - conda-forge

dependencies:
  # Required
  - argopy>=1.2
  - cartopy
  - contourpy
  - erddapy<3  # erddapy 3 breaks argopy's imports
  - matplotlib
  - netCDF4
  - numba
  - numpy
  - psutil
  - scipy
  - threadpoolctl
  - xarray
  - xoa
  # Optional
  - cmocean
  - colorlog
  - dask
  - gsw
  - owslib
  - pooch
  # Tests
  - pytest
