name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: "3.11"  # as in .pre-commit-config.yaml
      - uses: pre-commit/action@v3.0.1

  test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.12"]
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0  # version from git tags
      - uses: conda-incubator/setup-miniconda@v4
        with:
          miniforge-version: latest
          environment-file: env/environment.yml
          activate-environment: shoot
          python-version: ${{ matrix.python-version }}
      - name: Install shoot
        run: pip install --no-deps .
      - name: Test with pytest
        run: pytest

  docs:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: conda-incubator/setup-miniconda@v4
        with:
          miniforge-version: latest
          environment-file: env/environment.yml
          activate-environment: shoot
          python-version: "3.12"
      - name: Install shoot and sphinx
        run: |
          pip install --no-deps .
          pip install sphinx sphinx-argparse sphinx-book-theme sphinx-gallery sphinxcontrib-programoutput
      - name: Build the docs without running the examples
        run: sphinx-build -b html -D sphinx_gallery_conf.plot_gallery=0 docs docs/_build/html
